---
- name: install python & devel. packages for venv setup
  apt: name="{{ item }}" update_cache=yes
  with_items: '{{ core_django_packages }}+{{ django_packages }}'
  become: true
  tags: superuser

- name: create app base directory
  file: name='{{ app_base_path }}' state=directory

- name: install venv itself using pip
  pip: name=virtualenv state=latest executable='pip{{ py_ver }}'
  become: true
  tags: superuser

- name: setup venv & ensure pip is fresh
  pip: name=pip state=latest virtualenv='{{ venv_path }}'

- name: pull application from repo
  git:
    repo: "{{ git_repo }}"
    key_file: '{{ git_private_key }}'
    version: "{{ branch }}"
    accept_hostkey: True
    dest: "{{ app_path }}"
    recursive: '{{ git_recursive }}'
    umask: '{{ git_umask }}'
    depth: '{{ git_depth }}'
    force: yes
  register: git
  changed_when: (git.after is not defined) or (git.after != git.before)
  when: 
    - git_repo is defined
    - git_repo is not none
  notify: "reload app"
  tags: upgrade

- name: install pip requirements
  pip: virtualenv='{{ venv_path }}' requirements='{{ requirements_path }}'
  when: (git is defined and git.changed) or force_venv or git_repo is undefined
  tags: upgrade

- name: configure django settings
  template:
    src: "{{ django_settings_tpl }}"
    dest: "{{ django_settings_path }}"
  when: django_settings_tpl is defined
  notify: "reload app"
  tags: upgrade

- block:
  - name: run manage.py
    django_manage:
      command: "{{ item }}"
      app_path: "{{ app_path }}"
      virtualenv: "{{ venv_path }}"
    with_items: '{{ django_commands }}'
    when: (git is defined and git.changed) or force_manage or git_repo is undefined

  - name: load fixtures
    django_manage:
      command: loaddata
      app_path: "{{ app_path }}"
      virtualenv: "{{ venv_path }}"
      fixtures: "{{ django_fixtures|default([])|join(' ') }}"
    when: django_fixtures

  - name: create superusers
    django_manage:
      command: '
        createsuperuser --noinput
          {% if item.email is defined %}--email {{ item.email }}{% endif %}
          {% if item.username is defined %}--username {{ item.username }}{% endif %}
      '
      virtualenv: '{{ venv_path }}'
      app_path: '{{ app_path }}'
    with_items: '{{ django_admins }}'

  - name: install pexpect
    apt: name=python-pexpect
    become: true
    when: django_admins|length>0 or django_users|length>0
    tags: superuser

  - name: change passwords
    expect:
      chdir: '{{ app_path }}'
      command: '{{ venv_path }}/bin/python{{ py_ver }} manage.py changepassword {{ item.user }}'
      responses:
        Password: '{{ item.pass }}'
    with_items: '{{ django_admins|union(django_users) }}'

  ignore_errors: django_ignore_manage_erros
  environment:
    DJANGO_SETTINGS_MODULE: "{{ django_settings_module }}"
  tags: upgrade
